apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui-deploy
  labels:
    tier: frontend
    app: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      name: openwebui
      labels:
        app: openwebui
    spec:
      containers:
        - name: openwebui
          image: ghcr.io/open-webui/open-webui:latest
          env:
            - name: OPENAI_API_BASE_URL
              value: http://vllm-service:8000/v1
          ports:
            - containerPort: 8080